/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EditorDeCitas.FrontEnd;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblpaciente = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblBuscaCitas = new javax.swing.JLabel();
        lblBuscacita = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backroud2 = new javax.swing.JTextField();
        backroud = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/magnifying-glass_10020288.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 140, 30));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 380, 80));

        lblpaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblpaciente.setText("Paciente:");
        bg.add(lblpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, 20));

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/clock_13321011.png"))); // NOI18N
        lblHora.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bg.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 190, 30));

        lblPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/person_13371705.png"))); // NOI18N
        lblPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bg.add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 210, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Hora:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 40, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Motivo:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID de Cita");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 40));

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/calendar_11133975.png"))); // NOI18N
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bg.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 40));

        lblBuscaCitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscaCitas.setForeground(new java.awt.Color(0, 102, 204));
        lblBuscaCitas.setText("Buscar Cita");
        lblBuscaCitas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bg.add(lblBuscaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 590, 110));

        lblBuscacita.setBackground(new java.awt.Color(153, 153, 153));
        lblBuscacita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscacita.setForeground(new java.awt.Color(0, 102, 204));
        lblBuscacita.setText("Datos de cita");
        lblBuscacita.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bg.add(lblBuscacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 590, 270));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 590, 270));
        bg.add(backroud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 200, 30));

        javax.swing.GroupLayout backroudLayout = new javax.swing.GroupLayout(backroud);
        backroud.setLayout(backroudLayout);
        backroudLayout.setHorizontalGroup(
            backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        backroudLayout.setVerticalGroup(
            backroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        bg.add(backroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 590, 120));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/floppy-disk_2037.png"))); // NOI18N
        btnSave.setText("GUARDAR");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        bg.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 170, 40));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditorDeCitas/FrontEnd/delete_16480390.png"))); // NOI18N
        btnDelete.setText("CANCELAR");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bg.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }
    public JButton getBtnBuscar() {
        return jButton1;
    }

    public JButton getBtnGuardar() {
        return btnSave;
    }

    public JTextField getTxtId() {
        return backroud2;
    }

    public JTextField getTxtMotivo() {
        return jTextField1;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public JLabel getLblPaciente() {
        return lblPaciente;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backroud;
    private javax.swing.JTextField backroud2;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBuscaCitas;
    private javax.swing.JLabel lblBuscacita;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblpaciente;
    // End of variables declaration//GEN-END:variables
}
